pipeline {
    agent none
    
    stages {
      stage('Back-end') {
        agent {
          docker { image 'maven:3.8.1-adoptopenjdk-11' }
        }
        steps {
          sh 'mvn --version' // Display Maven version
          
          // Compile and run the Java "Hello World" application
          sh 'echo public class HelloWorld { public static void main(String[] args) { System.out.println("Hello, World!"); } } > HelloWorld.java'
          sh 'javac HelloWorld.java'
          sh 'java HelloWorld'
          
          // Install dependencies using Maven
          sh 'mvn clean install'
        }
      }
      stage('Front-end') {
        agent {
          docker { image 'node:16-alpine' }
        }
        steps {
          sh 'node --version' // Display Node.js version
          
          // Display a simple message for the "Hello World" application
          sh 'echo "Hello, World!"'
          
          // Install dependencies using npm
          sh 'npm install'
        }
      }
    }
  }
  
